blog/urls.py
from django.urls import path

from .views import (BlogListView, BlogDetailView,
                    BlogCreateView, BlogUpdateView,
                    BlogDeleteView, follower_list, following_list,
                    CommentCreateView, LikeView,
                    LikeViewHome, MyPDF, )

urlpatterns = [
    path(
        '',
        BlogListView.as_view(),
        name='home'
    ),
    path(
        'post/<int:pk>/',
        BlogDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'blogpost-like/<int:pk>/', LikeView.as_view(),
        name="blogpost_like"
    ),

    path(
        r'^pdf/(?P<pk>\d+)/$',
        MyPDF.as_view(template_name='post_detail.html',
                      filename='post_pdf.pdf'),
        name='pdf-wk'
    ),

    path(
        'post/new/', BlogCreateView.as_view(),
        name='post_new'
    ),
    path(
        'comment/<int:pk>/', CommentCreateView.as_view(),
        name='post_comment'
    ),

    path(
        'post-like/<int:pk>', LikeViewHome.as_view(),
        name="post_like"
    ),
    path(
        'post/<int:pk>/edit/',
        BlogUpdateView.as_view(),
        name='post_edit'
    ),
    path(
        'post/<int:pk>/delete/',
        BlogDeleteView.as_view(),
        name='post_delete'
    ),

    path(
        'follower_list/',
        follower_list,
        name='follower-list'
    ),
    path(
        'following_list/',
        following_list,
        name='following-list'
    ),

]

blog_project/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('accounts.urls')),
    path('api/v1/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles ')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/rest-auth/', include('rest_auth.urls')),
    url('auth/', include('djoser.urls.jwt')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from .views import ProfilesDetailView, FollowView

app_name = 'profiles'

urlpatterns = [
    path('switch/', FollowView.as_view(), name='follow-unfollow-view'),
    path('<pk>/', ProfilesDetailView.as_view(), name='profile-detail-view'),

]

templates/base.html
{% load static %}
<html>
<head>

    <title>Django blog</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

</head>
<body>


<header style="background-color: #9d9d9d;">

    <div class="nav-left">
    <h1><a href="{% url 'home' %}">Django blog</a></h1>
    </div>

    {% if user.is_authenticated %}
    <div class="nav-right">
    <a href="{% url 'post_new' %}">+ New Blog Post</a>
    </div>
    {% endif %}

</header>
<div>
    {% if user.is_authenticated %}
    <p>Hi, <b>{{ res|default:user.email|cut:"@gmail.com"|upper }}</b>!</p>

    <p><a href="{% url 'logout' %}">Log out</a></p>
    {% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a> |
    <a href="{% url 'signup' %}">Sign-Up</a>
    {% endif %}
        {% block content %}
        {% endblock content %}
</div>
</body>
</html>

templates/comment.html
<!{% extends 'base.html' %}
{% block content %}



<form action="" method="post" id="comment_form">{% csrf_token %}
        <div>{{ form.as_p }}</div>
<!--  <textarea rows="2" cols="40" form="comment_form" name="txt_comment" placeholder="Enter Your Comment here...">-->
<!--</textarea>-->
  <input type="submit">
</form>


 {% endblock content %}

templates/follower_list.html
<!{% extends 'base.html' %}
{% block content %}

   <head>
      <title>HTML Table Cellpadding</title>
   </head>

   <body>



      <table style="background-color: #918b8b52;" border = "1" cellpadding = "5" cellspacing = "5">


          <th>Follower</th>

        {% for follower in  user.follower.all %}

         <tr>
           <td>{{ follower }}</td>
         </tr>


{% endfor %}


      </table>
 {% endblock content %}

templates/following_list.html
{% extends 'base.html' %}
{% block content %}

   <body>
      <table border = "1" cellpadding = "5" cellspacing = "5">
          <th>Following</th>

        {% for following in  user.following.all %}
         <tr>
           <td>{{ following }}</td>
         </tr>
{% endfor %}
      </table>

   {% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}

{% if user.is_authenticated %}
<button class="btn_count" type="submit"><b>{{ user_follower }}</b>
    <a href="{% url 'follower-list' %}">Followers</a></button>
<button class="btn_count" type="submit"><b>{{ user_count }}</b>
  <a href="{% url 'following-list' %}">Following</a></button>
<br>
{% endif %}
<table border = "1" style="width:100%">
    {% for post in object_list reversed %}




    <tr>
        <td>
<div class="post-entry column">
    <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>


            <form action="{% url 'post_like' post.pk %}" method="POST">
	{% csrf_token %}

	{% if post_is_liked %}
<!--            <button type="submit" name="blogpost_id" value="{{object.id}}" onclick="myFunction(this)" class="fa fa-thumbs-down" ></button>-->

	<button type="submit" name="post_id" value="{{post.pk}}" >Unlike</button>
	{% else %}
<!--            <button type="submit" name="blogpost_id" value="{{object.id}}" onclick="myFunction(this)" class="fa fa-thumbs-up" ></button>-->

	<button type="submit" name="post_id" value="{{post.pk}}" >Like</button>
	{% endif %}
  </form>






     <p>{{ post.body }}</p>

{% if post.image %}
    <img style="width:10%; height:50px;" src="{{post.image.url}}"/>

    {% endif %}
</div>
        </td>
    </tr>



{% endfor %}
</table>

<style>
 .column {
  float: left;
  width: 97.5%;
  padding: 10px;
  background-color:#ddd;
}
</style>
{% if user.is_authenticated %}
<a href="api/v1/post/?title__contains=">api |</a>
<a href="auth/jwt/create/">generate token |</a>
<a href="auth/jwt/refresh/">refresh</a>{% endif %}
<a href="">OTher |</a>
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete post</h1>
<form action="" method="post">
    {% csrf_token %}

<p>Are you sure you want to delete "{{ post.title }}"?</p>
<input type="submit" value="Confirm" />

</form>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}


{% block content %}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.fa {
  font-size: 50px;
  cursor: pointer;
  user-select: none;
}

.fa:hover {
  color: darkblue;
}
</style>
<script>
function myFunction(x) {
  x.classList.add("fa-thumbs-up");
  x.classList.remove("fa-thumbs-down");
}
</script>
<hr style="display: block; margin-before: 0.5em; margin-after: 0.5em; margin-start: auto;
 margin-end: auto; overflow: hidden; border-style: inset; border-width: 10px;"
    ></hr>

<div class="post-entry">
    <h2> {{ post.title }}</h2>
<hr style="  border-style: solid; border-width: 3px;"
    ></hr>
<br>
    <p>Author: <i>{{ post.author|cut:"@gmail.com" }}</i></p>
<button class="btn_count" type="submit"><b>{{ follower_count }}</b>
        Followers
</button>

<button class="btn_count" type="submit"><b>{{ following_count }}</b> Followings</button>
    <p>{{ post.body }}</p>


    <a href="{% url 'pdf-wk' post.pk %}">PDF WKHTML</a><br>



    <!-- LIKES -->
{% if user.is_authenticated %}
  <form action="{% url 'blogpost_like' post.id %}" method="POST">
	{% csrf_token %}

	{% if post_is_liked %}
            <button type="submit" name="blogpost_id" value="{{object.id}}" onclick="myFunction(this)" class="fa fa-thumbs-down" ></button>

<!--	<button type="submit" name="blogpost_id" value="{{object.id}}" >Unlike</button>-->
	{% else %}
            <button type="submit" name="blogpost_id" value="{{object.id}}" onclick="myFunction(this)" class="fa fa-thumbs-up" ></button>

<!--	<button type="submit" name="blogpost_id" value="{{object.id}}" >Like</button>-->
	{% endif %}
  </form>

{% endif %}
<strong class="text-secondary">{{ number_of_likes }} Like{{ number_of_likes|pluralize }}</strong>
<br>

{% if post.image %}
    <img src="{{post.image.url}}" />

    {% endif %}
</div>

{% if user == post.author %}
{% else %}
            {% if follow %}
<form action="{% url 'profiles:follow-unfollow-view' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="profile_pk" value='{{ post.author }}'>
    <button class="btn1" type="submit">UNFOLLOW</button>
</form>
{% else %}
 <form action="{% url 'profiles:follow-unfollow-view'%}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="profile_pk" value='{{ post.author }}'>
    <button class="btn1" type="submit">FOLLOW</button>
     </form>
{% endif %}

</div>


{% endif %}

 {% if user == post.author %}
<a href="{% url 'post_edit' post.pk %}">+ Edit Blog Post</a>
<p><a href="{% url 'post_delete' post.pk %}">+ Delete Blog Post</a></p>
{% endif %}

<div>
<h3>Comments</h3>

<ul>
{% for comment in post.comments.all %}
   <i style=" font-style: italic; font-size: small;
    color: #000000b3;
    font-style: italic;"> <b>{{ comment.author|cut:'@gmail.com' }}</b> said <b>{{ comment.created_on|timesince }} ago</b></i>
<li>{{ comment.comments }} </li><br>

{% endfor %}
</ul>

 <a href="{% url 'post_comment' post.pk %}">+ Your Comment</a>

</div>



{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}
{% block content %}

<h1>Edit post</h1>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}
{% block content %}
    <h1>New post</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
       <div style="background-color: skyblue;"> {{ form.as_p }}</div>
    <div style="background-color: red;"> {{ user.username }}</div>
<input type="submit" value="Save" />

    </form>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
    <h2>Sign up</h2>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
<button type="submit">Sign up</button>
</form>
{% endblock content %}

templates/temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>temp.html</h1>
 <img src="/home/mehrab/blogapi_change bd final (custom model)/media/images/p.png" />
<img src="media/images/p2.png" />


<form action="{% url 'profiles:follow-unfollow-view' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="profile_pk" value=''>
    <button class="btn1" type="submit">UNFOLLOW</button>
</form>

 <form action="{% url 'profiles:follow-unfollow-view'%}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="profile_pk" value=''>
    <button class="btn1" type="submit">FOLLOW</button>
     </form>

<a href="">+ Edit Blog Post</a>
<p><a href="">+ Delete Blog Post</a></p>
<p>loop</p>
 {% for post in object_list %}

    <img src="{{post.image.url}}" />
{{ post.title }}
 {{ post.body }}

 {% endfor%}
</body>
</html>